// Code generated by "stringer -type Operator"; DO NOT EDIT.

package telnet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Se-240]
	_ = x[Nop-241]
	_ = x[DataMark-242]
	_ = x[Break-243]
	_ = x[Interrupt-244]
	_ = x[Abort-245]
	_ = x[AreYouThere-246]
	_ = x[EraseChar-247]
	_ = x[EraseLine-248]
	_ = x[GoAhead-249]
	_ = x[Subnegotiation-250]
	_ = x[Will-251]
	_ = x[Wont-252]
	_ = x[Do-253]
	_ = x[Dont-254]
	_ = x[Iac-255]
	_ = x[BinaryTransmission-0]
	_ = x[Echo-1]
	_ = x[Reconnection-2]
	_ = x[SuppressGoAhead-3]
	_ = x[ApproxMessageSizeNegotiation-4]
	_ = x[Status-5]
	_ = x[TimingMark-6]
	_ = x[RemoteControlledTransAndEcho-7]
	_ = x[OutputLineWidth-8]
	_ = x[OutputPageSize-9]
	_ = x[OutputCarriageReturnDisposition-10]
	_ = x[OutputHorizontalTabStops-11]
	_ = x[OutputHorizontalTabDisposition-12]
	_ = x[OutputFormfeedDisposition-13]
	_ = x[OutputVerticalTabstops-14]
	_ = x[OutputVerticalTabDisposition-15]
	_ = x[OutputLinefeedDisposition-16]
	_ = x[ExtendedASCII-17]
	_ = x[Logout-18]
	_ = x[ByteMacro-19]
	_ = x[DataEntryTerminal-20]
	_ = x[SUPDUP-21]
	_ = x[SUPDUPOutput-22]
	_ = x[SendLocation-23]
	_ = x[TerminalType-24]
	_ = x[EndofRecord-25]
	_ = x[TACACSUserIdentification-26]
	_ = x[OutputMarking-27]
	_ = x[TerminalLocationNumber-28]
	_ = x[Telnet3270Regime-29]
	_ = x[X3PAD-30]
	_ = x[NegotiateAboutWindowSize-31]
	_ = x[TerminalSpeed-32]
	_ = x[RemoteFlowControl-33]
	_ = x[Linemode-34]
	_ = x[XDisplayLocation-35]
	_ = x[ExtendedOptionsList-36]
}

const (
	_Operator_name_0 = "BinaryTransmissionEchoReconnectionSuppressGoAheadApproxMessageSizeNegotiationStatusTimingMarkRemoteControlledTransAndEchoOutputLineWidthOutputPageSizeOutputCarriageReturnDispositionOutputHorizontalTabStopsOutputHorizontalTabDispositionOutputFormfeedDispositionOutputVerticalTabstopsOutputVerticalTabDispositionOutputLinefeedDispositionExtendedASCIILogoutByteMacroDataEntryTerminalSUPDUPSUPDUPOutputSendLocationTerminalTypeEndofRecordTACACSUserIdentificationOutputMarkingTerminalLocationNumberTelnet3270RegimeX3PADNegotiateAboutWindowSizeTerminalSpeedRemoteFlowControlLinemodeXDisplayLocationExtendedOptionsList"
	_Operator_name_1 = "SeNopDataMarkBreakInterruptAbortAreYouThereEraseCharEraseLineGoAheadSubnegotiationWillWontDoDontIac"
)

var (
	_Operator_index_0 = [...]uint16{0, 18, 22, 34, 49, 77, 83, 93, 121, 136, 150, 181, 205, 235, 260, 282, 310, 335, 348, 354, 363, 380, 386, 398, 410, 422, 433, 457, 470, 492, 508, 513, 537, 550, 567, 575, 591, 610}
	_Operator_index_1 = [...]uint8{0, 2, 5, 13, 18, 27, 32, 43, 52, 61, 68, 82, 86, 90, 92, 96, 99}
)

func (i Operator) String() string {
	switch {
	case i <= 36:
		return _Operator_name_0[_Operator_index_0[i]:_Operator_index_0[i+1]]
	case 240 <= i && i <= 255:
		i -= 240
		return _Operator_name_1[_Operator_index_1[i]:_Operator_index_1[i+1]]
	default:
		return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
