services:
  chown:
    image: alpine
    command: chown -R 1000:1000 /data
    volumes:
      - data:/data

  app:
    image: "ghcr.io/gabe565/ascii-movie"
    build: .
    environment:
      COLORTERM: "$COLORTERM"
      TERM: "$TERM"
      ASCII_MOVIE_SSH_ADDRESS: ":2222"
      ASCII_MOVIE_TELNET_ADDRESS: ":2323"
      ASCII_MOVIE_API_ADDRESS: ":1977"
    ports:
      - "2323:2323"
      - "2222:2222"
      - "127.0.0.1:1977:1977"
    read_only: true
    restart: unless-stopped
    depends_on:
      chown:
        condition: service_completed_successfully
    volumes:
      - data:/data
    develop:
      watch:
        - action: rebuild
          path: .

volumes:
  data: {}
