version: "3.9"

services:
  app:
    image: "ghcr.io/gabe565/ascii-movie"
    build: .
    environment:
      COLORTERM: "$COLORTERM"
      TERM: "$TERM"
      ASCII_MOVIE_API_ADDRESS: ":1977"
    ports:
      - "23:23"
      - "2222:22"
      - "127.0.0.1:1977:1977"
