FROM alpine:3.19

RUN apk add --no-cache tzdata

ARG USERNAME=ascii-movie
ARG UID=1000
ARG GID=$UID
RUN addgroup -g "$GID" "$USERNAME" \
    && adduser -S -u "$UID" -G "$USERNAME" "$USERNAME"

COPY ascii-movie /bin
ENV TERM=xterm-256color
USER $UID
ENTRYPOINT ["ascii-movie"]
CMD ["serve"]
