version: "3.9"

services:
  chown:
    image: alpine
    command: chown -R 1000:1000 /data
    volumes:
      - data:/data

  app:
    image: "ghcr.io/gabe565/ascii-movie"
    build: .
    environment:
      COLORTERM: "$COLORTERM"
      TERM: "$TERM"
      ASCII_MOVIE_API_ADDRESS: ":1977"
    ports:
      - "23:23"
      - "2222:22"
      - "127.0.0.1:1977:1977"
    read_only: true
    depends_on:
      chown:
        condition: service_completed_successfully
    volumes:
      - data:/data

volumes:
  data: {}
